apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000  # This should match the port your app is listening on
  type: LoadBalancer  # Use ClusterIP or NodePort based on your Kubernetes setup
